### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by databuzz** [matatirosolutions/fm-cloud-authentication#1]
I'm trying this out for the first time and have setup a simple php file to get the $token and echo that back out. I'm getting a 500 error in the Apache error_log, but it feels like something is happening here as I'm getting the SMS from Claris with my 2 factor login token and also getting the 'New sign-in attempt' email each time I load the php file.

I'm using your example for testing this out:

`require_once __DIR__ . '/vendor/autoload.php';

$credentials = new \MSDev\FMCloudAuthenticator\Credentials(
    'your-fm-cloud-server',
    'your-fmrest-user',
    'your-fmrest-password',
    \MSDev\FMCloudAuthenticator\Credentials::DAPI,
    'your-database'
);

$authenticator = new \MSDev\FMCloudAuthenticator\Authenticate();
$token = $authenticator->fetchToken($credentials);`

updated with the credentials for my FileMaker Cloud server/user/database. Here's what I'm seeing in the Apache error_log:

`Got error 'PHP message: PHP Notice:  Trying to access array offset on value of type null in /opt/bitnami/apache/htdocs/filemaker_cloud_data_api/vendor/matatirosoln/fm-cloud-authentication/src/Authenticate.php on line 63PHP message: PHP Fatal error:  Uncaught TypeError: Return value of MSDev\\FMCloudAuthenticator\\Authenticate::getCognitoToken() must be of the type string, null returned in /opt/bitnami/apache/htdocs/filemaker_cloud_data_api/vendor/matatirosoln/fm-cloud-authentication/src/Authenticate.php:63\nStack trace:\n#0 /opt/bitnami/apache/htdocs/filemaker_cloud_data_api/vendor/matatirosoln/fm-cloud-authentication/src/Authenticate.php(32): MSDev\\FMCloudAuthenticator\\Authenticate->getCognitoToken()\n#1 /opt/bitnami/apache/htdocs/filemaker_cloud_data_api/getToken.php(17): MSDev\\FMCloudAuthenticator\\Authenticate->fetchToken()\n#2 {main}\n\nNext MSDev\\FMCloudAuthenticator\\Exception\\AuthenticationException: Return value of MSDev\\FMCloudAuthenticator\\Authenticate::getCognitoToken() must be of the type string, null returned in /opt/bitnami/apache/htdocs/filemaker_cloud_data_api/vendor/matatirosoln/fm-cloud-authentication/src/Authenticate.php:34\nStack trace:\n#0 /opt/bitnami/apache/htdocs/filemaker_cloud_data_api/getToken.php(17): M...'`

**Comment by steveWinter** [comment]
I've not been successful in getting this to work with an account on which 2FA is enabled. There's the extra hoop which needs to be jumped through in order to be able to submit that back and given that the purpose for which this was written was 'headless operation' of a web application or API then there won't be anyone to provide that response anyway so I haven't gone further into solving this. In short, use an account which doesn't have 2FA enabled.

In terms of the email about the new login - that's a continuing struggle with Claris as well since the approval must come from the same IP address as is making the authentication attempt in order for it to be accepted. That's fine in testing so long as you're on the same network as the PHP. In production it can become more difficult since most web servers don't have a desktop, and so don't have a browser (and you can't use cURL to approve the IP because it's a front-end application used for the approval and consequently requires JavaScript). The only known workaround is that you have to email (yes really) Claris tech support with the IP address you wish to connect from and the email address of the account. They will then manually enter an approval for that combination.

I have found that if you use a 'brand new' account which has never logged in from anywhere, and it makes its first ever login attempt using this library then that will be accepted (since it's not a new location, it's the first and only one) but you can't then move the operation to a new IP (e.g. when you move from testing to production) without then having to get the new IP approved.

In the back of my mind I have this idea that I could write something which can deal with the IP approval using headless Chrome or the like but haven't come back to that as yet.

**Comment by databuzz** [comment]
Thanks - I'll disable 2FA and re-test. I'm running this on an AWS Linux server so cannot login via a web browser either - have emailed Claris Support to get this approved and will test again once I hear back from them. Thanks for the quick reply :-)
